spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    # driver for jdbc
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # auto drop and create table from entity
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true # not recommended - using sout
        format_sql: true

logging.level:
  # show executed SQL
  org.hibernate.SQL: debug
  # show transaction (commit, rollback)
  org.hibernate.resource.transaction: debug
  org.springframework.orm.jpa.JpaTransactionManager: debug
  # show binding parameter
  org.hibernate.orm.jdbc.bind: trace

server:
  error:
    include-stacktrace: never
